insert into restaurant (city, state, street, zip_code, name) values ('Fairfiled','IA','1000 NT 4th street',52557,'Anapurna 1');
insert into restaurant (city, state, street, zip_code, name) values ('Fairfiled','IA','1000 NT 4th street',52557,'Anapurna 2');
insert into dining_table(capacity) values ( 4 );
insert into dining_table(capacity) values ( 4 );
insert into dining_table(capacity) values ( 4 );
insert into dining_table(capacity) values ( 4 );
insert into dining_table(capacity) values ( 4 );
insert into dining_table(capacity) values ( 4 );
insert into dining_table(capacity) values ( 4 );
insert into dining_table(capacity) values ( 4 );
insert into dining_table(capacity) values ( 4 );
insert into dining_table(capacity) values ( 4 );
insert into dining_table(capacity) values ( 4 );
insert into dining_table(capacity) values ( 4 );
insert into dining_table(capacity) values ( 4 );
insert into dining_table(capacity) values ( 4 );
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (1,1);
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (1,2);
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (1,3);
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (1,4);
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (1,5);
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (1,6);
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (1,7);
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (2,8);
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (2,9);
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (2,10);
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (2,11);
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (2,12);
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (2,13);
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (2,14);